# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres:11-alpine
    #     ports:
    #       - "5432:5432"
    #     env:
    #       POSTGRES_DB: rails_test
    #       POSTGRES_USER: rails
    #       POSTGRES_PASSWORD: password
    # env:
    #   RAILS_ENV: test
    #   DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here

      - name: Install Ruby and gems
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file

          
      # Add or replace database setup steps here
      # - name: Set up database schema
      #   run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Load Transform
        run: load 'transform.rb' 

      - name: Run
        run: run 

      - name: Upload data
        uses: actions/upload-artifact@v4.3.6
        with:
          name: for_shopify.csv
          path: for_shopify.csv

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
  #       with:
  #         bundler-cache: true
  #     - name: Generate binstubs
  #       run: bundle binstubs bundler-audit brakeman rubocop
  #     # Add or replace any other lints here
  #     - name: Security audit dependencies
  #       run: bin/bundler-audit --update
  #     - name: Security audit application code
  #       run: bin/brakeman -q -w2
  #     - name: Lint Ruby files
  #       run: bin/rubocop --parallel
